name: CI
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release version
        id: release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{steps.release.outputs}}
